features = {
    "info_pre_filter": {
        "livetime",
        "likelihood",
        "pileup_flag",
        "mstr_sat_src_flag",
        "mstr_streak_src_flag",
        "gti_obs",
        "flux_significance_b",
        "flux_significance_m",
        "flux_significance_s",
        "flux_significance_h",
        "flux_significance_u",
    },
    "info": {
       
        "class",
        "src_n",
        "src_id",
        "significance",
    },
    "flux": {
        "photon": {
            "photflux_aper_hilim_s",
            "photflux_aper_hilim_u",
            "photflux_aper_hilim_m",
            "photflux_aper_hilim_h",
            "photflux_aper_hilim_b",
            "photflux_aper_lolim_s",
            "photflux_aper_lolim_u",
            "photflux_aper_lolim_m",
            "photflux_aper_lolim_h",
            "photflux_aper_lolim_b",
            "photflux_aper_s",
            "photflux_aper_u",
            "photflux_aper_m",
            "photflux_aper_h",
            "photflux_aper_b",
        },
        "energy": {
            "flux_aper_hilim_s",
            "flux_aper_hilim_u",
            "flux_aper_hilim_m",
            "flux_aper_hilim_h",
            "flux_aper_hilim_b",
            "flux_aper_lolim_s",
            "flux_aper_lolim_u",
            "flux_aper_lolim_m",
            "flux_aper_lolim_h",
            "flux_aper_lolim_b",
            "flux_aper_s",
            "flux_aper_u",
            "flux_aper_m",
            "flux_aper_h",
            "flux_aper_b",
            "flux_aper_hilim",
            "flux_aper_lolim",
            "flux_aper",
            "photflux_aper_hilim",
            "photflux_aper_lolim",
            "photflux_aper",
        },
    },
    "variability": {
        "var_index",
        "var_prob",
        "ks_prob",
        "kp_prob",
        "var_sigma",
        "var_mean",
        "var_min",
        "var_max",
        "var_inter_index",
        "var_inter_prob",
        "var_inter_sigma",
    },
    "hardness": {
        "hard_hm",
        "hard_hm_hilim",
        "hard_hm_lolim",
        "hard_hs",
        "hard_ms",
        "hard_hs_hilim",
        "hard_hs_lolim",
        "hard_ms_hilim",
        "hard_ms_lolim",
    },
    "model_fit": {
        "powerlaw": {
            "flux_powlaw" , 
            "flux_powlaw_lolim" ,
            "flux_powlaw_hilim" , 
            "powlaw_gamma",
            "powlaw_gamma_hilim",
            "powlaw_gamma_lolim",
            "powlaw_nh",
            "powlaw_nh_hilim",
            "powlaw_nh_lolim",
            "powlaw_ampl",
            "powlaw_ampl_hilim",
            "powlaw_ampl_lolim",
            "powlaw_stat",
        },
        "bb": {
            "flux_bb", 
            "flux_bb_lolim" , 
            "flux_bb_hilim" , 
            "bb_kt",
            "bb_kt_hilim",
            "bb_kt_lolim",
            "bb_nh_hilim",
            "bb_nh_lolim",
            "bb_nh",
            "bb_ampl",
            "bb_ampl_lolim",
            "bb_ampl_hilim",
            "bb_stat",
        },
        "brems": {
            "brems_kt",
            "brems_kt_hilim",
            "brems_kt_lolim",
            "brems_nh",
            "brems_nh_hilim",
            "brems_nh_lolim",
            "brems_stat",
        },
    },
}
