rows = [
     "B_SIGNIFICANCE",

        "B_FLUX_BB",
        "B_FLUX_BREMS",
        "B_FLUX_PLAW",

        "B_B_FLUX_AP",
        "B_B_FLUX_AP90",
        "B_B_FLUX_AP90_AVG",
        "B_B_FLUX_AP_AVG",
        "B_B_FLUX_BB_AP",
        "B_B_FLUX_BB_AP90",
        "B_B_FLUX_BREMS_AP",
        "B_B_FLUX_BREMS_AP90",
        "B_B_FLUX_PLAW_AP",
        "B_B_FLUX_PLAW_AP90",

        "B_B_PHOTFLUX_AP",
        "B_B_PHOTFLUX_AP90",
        "B_B_PHOTFLUX_AP90_AVG",
        "B_B_PHOTFLUX_AP_AVG",



        "B_H_PHOTFLUX_AP",
        "B_H_PHOTFLUX_AP90",
        "B_H_PHOTFLUX_AP90_AVG",
        "B_H_PHOTFLUX_AP_AVG",

        "B_H_FLUX_AP",
        "B_H_FLUX_AP90",
        "B_H_FLUX_AP90_AVG",
        "B_H_FLUX_AP_AVG",
        "B_H_FLUX_APEC_AP",
        "B_H_FLUX_BB_AP",
        "B_H_FLUX_BB_AP90",
        "B_H_FLUX_BREMS_AP",
        "B_H_FLUX_BREMS_AP90",
        "B_H_FLUX_PLAW_AP",
        "B_H_FLUX_PLAW_AP90",



        "B_M_FLUX_AP90",
        "B_M_FLUX_AP",
        "B_M_FLUX_AP90_AVG",
        "B_M_FLUX_AP_AVG",
        "B_M_FLUX_BB_AP",
        "B_M_FLUX_BB_AP90",
        "B_M_FLUX_BREMS_AP",
        "B_M_FLUX_BREMS_AP90",
        "B_M_FLUX_PLAW_AP",
        "B_M_FLUX_PLAW_AP90",
        "B_M_PHOTFLUX_AP",
        "B_M_PHOTFLUX_AP90",
        "B_M_PHOTFLUX_AP90_AVG",
        "B_M_PHOTFLUX_AP_AVG",
        "B_M_POSITION_ANGLE",

        "B_U_FLUX_AP",
        "B_U_FLUX_AP90",
        "B_U_FLUX_AP90_AVG",
        "B_U_FLUX_AP_AVG",
        "B_U_FLUX_BB_AP",
        "B_U_FLUX_BB_AP90",
        "B_U_FLUX_BREMS_AP",
        "B_U_FLUX_BREMS_AP90",
        "B_U_FLUX_PLAW_AP",
        "B_U_FLUX_PLAW_AP90",
        "B_U_PHOTFLUX_AP",
        "B_U_PHOTFLUX_AP90",
        "B_U_PHOTFLUX_AP90_AVG",
        "B_U_PHOTFLUX_AP_AVG",


        "B_S_FLUX_AP",
        "B_S_FLUX_AP90",
        "B_S_FLUX_AP90_AVG",
        "B_S_FLUX_AP_AVG",
        "B_S_FLUX_BB_AP",
        "B_S_FLUX_BB_AP90",
        "B_S_FLUX_BREMS_AP",
        "B_S_FLUX_BREMS_AP90",
        "B_S_FLUX_PLAW_AP",
        "B_S_FLUX_PLAW_AP90",
        "B_S_FLUX_AP",
        "B_S_FLUX_AP90",
        "B_S_FLUX_AP90_AVG",
        "B_S_FLUX_AP_AVG",
        "B_S_FLUX_BB_AP",
        "B_S_FLUX_BB_AP90",
        "B_S_FLUX_BREMS_AP",
        "B_S_FLUX_BREMS_AP90",
        "B_S_FLUX_PLAW_AP",
        "B_S_FLUX_PLAW_AP90",
        "B_S_PHOTFLUX_AP",
        "B_S_PHOTFLUX_AP90",
        "B_S_PHOTFLUX_AP90_AVG",
        "B_S_PHOTFLUX_AP_AVG",
]